import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import "./globals.css"
import AuthProvider from "@/components/AuthProvider"
import { getServerSession } from "next-auth"
import { authOptions } from "./api/auth/[...nextauth]/options"

const montserrat = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Learn | Simple Project",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <AuthProvider session={session}>
        <body className={`${montserrat.className}  antialiased`}>
          {children}
        </body>
      </AuthProvider>
    </html>
  )
}
